# Quest

- Apakah ([1, 3]) adalah eigenvector dari matrix ([[1, -1], [6, 4]])

In [14]:
import numpy as np

In [20]:
%matplotlib inline
import matplotlib.pyplot as plt

In [15]:
from numpy.linalg import eig

In [24]:
from numpy.linalg import inv, det

In [25]:
A = np.array([[1, -1], [6,4]])

In [26]:
A

array([[ 1, -1],
       [ 6,  4]])

In [27]:
inv(A)

array([[ 0.4,  0.1],
       [-0.6,  0.1]])

In [4]:
eigval, eigvec = eig(A)

array([1, 3]) bukan merupakan eigenvector dari matrix array([[1, -1], [6, 4]])

In [5]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [6]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [10]:
from numpy import diag
diag(eigval)

array([[2.5+1.93649167j, 0. +0.j        ],
       [0. +0.j        , 2.5-1.93649167j]])

Rekonstruksi dengan eigenvalue dan eigenvector mendapati hasil metriks yang kurleb sama dengan metriks awal.

In [28]:
B = eigvec @ diag(eigval) @ inv(eigvec)

In [29]:
B

array([[ 1.+1.40042907e-16j, -1.-1.19871410e-17j],
       [ 6.+3.90480046e-16j,  4.-6.08328459e-17j]])