# Quest

- Apakah ([1, 3]) adalah eigenvector dari matrix ([[1, -1], [6, 4]])

In [1]:
import numpy as np

In [2]:
from numpy.linalg import eig

In [3]:
A = np.array([[1, -1], [6,4]])

In [4]:
A

array([[ 1, -1],
       [ 6,  4]])

In [5]:
eigval, eigvec = eig(A)

array([1, 3]) bukan merupakan eigenvector dari matrix array([[1, -1], [6, 4]])

In [6]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [7]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])