In [1]:
import numpy as np

# 1. Buatlah Tensor di bawah ini dengan Python 


In [6]:
A = np.array([[23, 50],[7, 12]])
B = np.array([[57, 67],[99, 43]])
C = np.array([[75,21], [57, 12]])
D = np.array([[87, 26], [18, 84]])

In [7]:
list_of_matrix = [A, B, C, D]
tensor = np.array(list_of_matrix)
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

jika dilihat dengan tensor.shape, sudah menjadi 3 dimensi (tensor)

In [8]:
tensor.shape

(4, 2, 2)

# 2. Perkalian terhadap matrix

In [12]:
X = np.array([[23, 50, 19], [7,12,109], [57,67,98]])
Y = np.array([[17], [22], [19]])

print(X)
print(" ")
print(Y)


[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
 
[[17]
 [22]
 [19]]


In [11]:
X @ Y

array([[1852],
       [2454],
       [4305]])

# 3 Lakukan Transpose, hitung determinan, dan inverse terhadap matrix :

In [14]:
Z = np.array([[23, 50, 19], [7,12,109], [57,67,98]])
print(Z)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


Transpose

In [17]:
Zt = Z.transpose()
Zt

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

Determinan

In [20]:
np.linalg.det(Z)

131344.0000000002

Inverse

In [21]:
np.linalg.inv(Z)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])